version: '3.8'

services:
  s_pdb:
    container_name: c_pdb
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - mynetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: gamzeiozsoy/backend:1.0.0
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://s_pdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - mynetwork
    depends_on:
      - s_pdb
    volumes:
      - backend-data:/app/data
  frontend:
    image: gamzeiozsoy/frontend:1.0.0
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  backend-data:
    driver: local